import React, { useState, useEffect } from 'react';
import {
  Box,
  Typography,
  TextField,
  Button,
  Paper,
  Autocomplete,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  IconButton,
  Divider,
  Card,
  CardContent,
  Alert,
  Stack,
} from '@mui/material';
import {
  Add as AddIcon,
  Delete as DeleteIcon,
  Save as SaveIcon,
  Cancel as CancelIcon,
} from '@mui/icons-material';
import { useBills } from '../../hooks/useBills';
import { useCustomers } from '../../hooks/useCustomers';
import { useProducts } from '../../hooks/useProducts';
import { Customer } from '../../types/customer';
import { Product } from '../../types/product';
import { Bill } from '../../types/bill';

interface BillFormProps {
  onClose?: () => void;
  showTitle?: boolean;
}

interface BillItem {
  productId: string;
  productName: string;
  quantity: number;
  price: number;
  total: number;
}

const BillForm: React.FC<BillFormProps> = ({ onClose, showTitle = true }) => {
  const { createBill } = useBills();
  const { customers, loading: customersLoading } = useCustomers();
  
  const { products, loading: productsLoading } = useProducts();

  const [selectedCustomer, setSelectedCustomer] = useState<Customer | null>(null);
  const [billItems, setBillItems] = useState<BillItem[]>([]);
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [quantity, setQuantity] = useState<number>(1);
  const [tax, setTax] = useState<number>(0);
  const [billDate, setBillDate] = useState<string>(new Date().toISOString().split('T')[0]);
  const [customLogo, setCustomLogo] = useState<File | null>(null);
  const [error, setError] = useState<string>('');

  const subtotal = billItems.reduce((sum, item) => sum + item.total, 0);
  const taxAmount = (subtotal * tax) / 100;
  const totalAmount = subtotal + taxAmount;

  const handleAddProduct = () => {
    if (!selectedProduct) {
      setError('Please select a product');
      return;
    }

    if (quantity <= 0) {
      setError('Quantity must be greater than 0');
      return;
    }

    const existingItemIndex = billItems.findIndex(item => item.productId === selectedProduct.id);
    
    if (existingItemIndex >= 0) {
      // Update existing item
      const updatedItems = [...billItems];
      updatedItems[existingItemIndex].quantity += quantity;
      updatedItems[existingItemIndex].total = updatedItems[existingItemIndex].quantity * selectedProduct.price;
      setBillItems(updatedItems);
    } else {
      // Add new item
      const newItem: BillItem = {
        productId: selectedProduct.id,
        productName: selectedProduct.name,
        quantity: quantity,
        price: selectedProduct.price,
        total: quantity * selectedProduct.price,
      };
      setBillItems([...billItems, newItem]);
    }

    setSelectedProduct(null);
    setQuantity(1);
    setError('');
  };

  const handleRemoveProduct = (productId: string) => {
    setBillItems(billItems.filter(item => item.productId !== productId));
  };

  const handleUpdateQuantity = (productId: string, newQuantity: number) => {
    if (newQuantity <= 0) {
      handleRemoveProduct(productId);
      return;
    }

    const updatedItems = billItems.map(item => {
      if (item.productId === productId) {
        return {
          ...item,
          quantity: newQuantity,
          total: newQuantity * item.price,
        };
      }
      return item;
    });
    setBillItems(updatedItems);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (!selectedCustomer) {
      setError('Please select a customer');
      return;
    }

    if (billItems.length === 0) {
      setError('Please add at least one product');
      return;
    }

    try {
      const newBill: Bill = {
        id: '', // Will be generated by the backend
        customerId: selectedCustomer.id,
        customerName: selectedCustomer.name,
        customerEmail: selectedCustomer.email,
        items: billItems,
        subtotal: subtotal,
        totalAmount: totalAmount,
        taxAmount: taxAmount,
        status: 'Draft',
        dueDate: billDate,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        logoUrl: customLogo ? URL.createObjectURL(customLogo) : undefined
      };

      await createBill(newBill);
      if (onClose) onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to create bill');
    }
  };

  return (
    <Box sx={{ p: 3, maxWidth: 1200, mx: 'auto' }}>
      {showTitle && (
        <Typography variant="h4" gutterBottom>
          Create New Bill
        </Typography>
      )}

      {error && (
        <Alert severity="error" sx={{ mb: 2 }}>
          {error}
        </Alert>
      )}

      <form onSubmit={handleSubmit}>
        <Stack spacing={3}>
          {/* Customer and Bill Details Row */}
          <Box sx={{ 
            display: 'grid', 
            gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' }, 
            gap: 3 
          }}>
            {/* Customer Selection */}
            <Card>
              <CardContent>
                <Typography variant="h6" gutterBottom>
                  Customer Details
                </Typography>
                <Autocomplete
                  options={customers}
                  getOptionLabel={(option) => `${option.name}`}
                  value={selectedCustomer}
                  onChange={(_, newValue) => setSelectedCustomer(newValue)}
                  loading={customersLoading}
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label="Select Customer"
                      required
                      fullWidth
                    />
                  )}
                />
                {selectedCustomer && (
                  <Box sx={{ mt: 2 }}>
                    <Typography variant="body2" color="text.secondary">
                      Email: {selectedCustomer.email}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      Phone: {selectedCustomer.phone}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      Address: {selectedCustomer.address}
                    </Typography>
                  </Box>
                )}
              </CardContent>
            </Card>

            {/* Bill Details */}
            <Card>
              <CardContent>
                <Typography variant="h6" gutterBottom>
                  Bill Details
                </Typography>
                <Stack spacing={2}>
                  <TextField
                    label="Bill Date"
                    type="date"
                    value={billDate}
                    onChange={(e) => setBillDate(e.target.value)}
                    fullWidth
                    InputLabelProps={{ shrink: true }}
                  />
                  <TextField
                    label="Tax (%)"
                    type="number"
                    value={tax}
                    onChange={(e) => setTax(Number(e.target.value))}
                    fullWidth
                    inputProps={{ min: 0, max: 100, step: 0.1 }}
                  />
                  <TextField
                    label="Upload Custom Logo"
                    type="file"
                    inputProps={{ accept: 'image/*' }}
                    onChange={(e) => {
                      const file = (e.target as HTMLInputElement).files?.[0];
                      setCustomLogo(file || null);
                    }}
                    fullWidth
                    InputLabelProps={{ shrink: true }}
                  />
                </Stack>
              </CardContent>
            </Card>
          </Box>

          {/* Product Selection */}
          <Card>
            <CardContent>
              <Typography variant="h6" gutterBottom>
                Add Products
              </Typography>
              <Box sx={{ 
                display: 'grid', 
                gridTemplateColumns: { xs: '1fr', md: '2fr 1fr 1fr' }, 
                gap: 2, 
                alignItems: 'start' 
              }}>
                <Box>
                  <Autocomplete
                    options={products}
                    getOptionLabel={(option) => option.name}
                    value={selectedProduct}
                    onChange={(_, newValue) => setSelectedProduct(newValue)}
                    loading={productsLoading}
                    renderInput={(params) => (
                      <TextField
                        {...params}
                        label="Select Product"
                        fullWidth
                      />
                    )}
                  />
                  {selectedProduct && (
                    <Box sx={{ mt: 1.5, ml: 0.5 }}>
                      <Typography variant="body2" color="text.secondary">
                        Product Name: {selectedProduct.name}
                      </Typography>
                      <Typography variant="body2" color="text.secondary">
                        Price: ₹{selectedProduct.price.toLocaleString()}
                      </Typography>
                      <Typography variant="body2" color="text.secondary">
                        Description: {selectedProduct.description || 'N/A'}
                      </Typography>
                    </Box>
                  )}
                </Box>
                <TextField
                  label="Quantity"
                  type="number"
                  value={quantity}
                  onChange={(e) => setQuantity(Number(e.target.value))}
                  fullWidth
                  inputProps={{ min: 1 }}
                />
                <Button
                  variant="contained"
                  startIcon={<AddIcon />}
                  onClick={handleAddProduct}
                  sx={{ height: 56 }}
                  disabled={!selectedProduct}
                >
                  Add Product
                </Button>
              </Box>
            </CardContent>
          </Card>
          

          {/* Bill Items Table */}
          {billItems.length > 0 && (
            <Card>
              <CardContent>
                <Typography variant="h6" gutterBottom>
                  Bill Items
                </Typography>
                <TableContainer component={Paper} variant="outlined">
                  <Table>
                    <TableHead>
                      <TableRow>
                        <TableCell>Product</TableCell>
                        <TableCell align="right">Price</TableCell>
                        <TableCell align="right">Quantity</TableCell>
                        <TableCell align="right">Total</TableCell>
                        <TableCell align="center">Actions</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {billItems.map((item) => (
                        <TableRow key={item.productId}>
                          <TableCell>{item.productName}</TableCell>
                          <TableCell align="right">₹{item.price.toLocaleString()}</TableCell>
                          <TableCell align="right">
                            <TextField
                              type="number"
                              value={item.quantity}
                              onChange={(e) => handleUpdateQuantity(item.productId, Number(e.target.value))}
                              size="small"
                              inputProps={{ min: 1, style: { textAlign: 'right' } }}
                              sx={{ width: 80 }}
                            />
                          </TableCell>
                          <TableCell align="right">₹{item.total.toLocaleString()}</TableCell>
                          <TableCell align="center">
                            <IconButton
                              color="error"
                              onClick={() => handleRemoveProduct(item.productId)}
                              size="small"
                            >
                              <DeleteIcon />
                            </IconButton>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </TableContainer>

                <Divider sx={{ my: 2 }} />
                

                {/* Bill Summary */}
                <Box sx={{ display: 'flex', justifyContent: 'flex-end' }}>
                  <Box sx={{ minWidth: 300 }}>
                    <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                      <Typography>Subtotal:</Typography>
                      <Typography>₹{subtotal.toLocaleString()}</Typography>
                    </Box>
                    <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                      <Typography>Tax ({tax}%):</Typography>
                      <Typography>₹{taxAmount.toLocaleString()}</Typography>
                    </Box>
                    <Divider />
                    <Box sx={{ display: 'flex', justifyContent: 'space-between', mt: 1 }}>
                      <Typography variant="h6">Total:</Typography>
                      <Typography variant="h6">₹{totalAmount.toLocaleString()}</Typography>
                    </Box>
                  </Box>
                </Box>
              </CardContent>
            </Card>
          )}

          {/* Action Buttons */}
          <Box sx={{ display: 'flex', gap: 2, justifyContent: 'flex-end' }}>
            <Button
              variant="outlined"
              startIcon={<CancelIcon />}
              onClick={onClose}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              variant="contained"
              startIcon={<SaveIcon />}
              disabled={!selectedCustomer || billItems.length === 0}
            >
              Create Bill
            </Button>
          </Box>
        </Stack>
      </form>
    </Box>
  );
};

export default BillForm;